[phases.setup]
nixPkgs = ["python311", "git"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'No build step required for Flask app'"]

[start]
cmd = "gunicorn run:app"
